# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9258422bc671f3012fb6f8b14857d29efb61fe7c915e80352723cbd4286d33a801288c905f2d0be5ba3d611fb15e2d7871bd869b2206433322469ce0eb5d4531

test:
  secret_key_base: 0ac764d983c8ba54f7bcb94d33d2bca6688fa2b2be66dcc80dbd4df8645478ad96da7bdea6ccd66029a4ffc39a248a4fc15c5bd7c5077b0f0cd62aa2a7b72246

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
